# Generated by Django 3.2.16 on 2023-02-12 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Юзернэйм')),
                ('telegram_id', models.CharField(max_length=30, verbose_name='Телеграм айди')),
            ],
        ),
        migrations.CreateModel(
            name='Valentine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(blank=True, verbose_name='Отправитель')),
                ('status', models.BooleanField(default=False, verbose_name='Статус валентинки')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Публичность')),
                ('text', models.TextField(blank=True, verbose_name='Коментарий к валентинке')),
                ('file_id', models.TextField(blank=True, verbose_name='Фото айди')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.user', verbose_name='Получатель')),
            ],
        ),
    ]
